#
#Sat Jul 18 14:51:34 MSK 2026
mail=weekend_game@mail.ru
javax.swing.JFrame_H=703
lang9=
lang8=
lang7=RU
lang6=EN
lang5=RU
lang4=EN
lang3=RU
lang2=EN
lang1=RU
lang0=EN
name6=CMS
name5=\u041F\u0440\u043E\u0441\u0442\u0430\u044F \u0431\u0438\u0431\u043B\u0438\u043E\u0442\u0435\u043A\u0430
name4=Simple library
name3=\u041F\u0440\u043E\u0441\u043C\u043E\u0442\u0440\u0449\u0438\u043A \u0431\u0430\u043D\u043A\u043E\u0432\u0441\u043A\u0438\u0445 \u0432\u044B\u043F\u0438\u0441\u043E\u043A
name9=
name8=
name7=CMS
javax.swing.JFrame_W=1080
name2=Bank statement viewer
projectName=Weekend game
srcFolder=./content
name1=\u0411\u043B\u043E\u0433
name0=Blog
javax.swing.JFrame_Y=49
javax.swing.JFrame_X=195
fileName16=
lang18=
fileName17=
lang17=
fileName18=
fileName19=
lang19=
fileName12=
lang14=
fileName13=
lang13=
fileName14=
lang16=
fileName15=
lang15=
javax.swing.JFrame_STATE=0
fileName10=
fileName11=
name19=
name18=
name17=
name16=
name15=
name14=
name13=
name12=
Language=EN
name11=
name10=
lang10=
lang12=
lang11=
fileName9=
fileName7=cms_ru.htm
fileName8=
dstFolder=../
gitSiteRU=https\://gitflic.ru/user/weekend-game
gitSiteEN=https\://github.com/weekend-game
mail2=weekend_game@mail.ru
mail1=my.weekend.game@gmail.com
fileName1=blog_ru.htm
fileName2=bankviewer.htm
fileName0=blog.htm
fileName5=simplelibrary_ru.htm
fileName6=cms.htm
fileName3=bankviewer_ru.htm
fileName4=simplelibrary.htm
